sudo: required
dist: trusty
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/work
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - CCACHE_SIZE=1G
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - PYTHON_DEBUG=1
  - WINEDEBUG=fixme-all
  - MAKEJOBS="-j2"
  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
  - BASE_PACKAGES="zip git build-essential libtool autotools-dev automake pkg-config
    bsdmainutils curl libevent-dev libssl-dev libdb4.8-dev libdb4.8++-dev libboost-all-dev
    python-dev"
  matrix:
  - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev python3
    nsis wine1.7 bc"
  - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev python3
    nsis wine1.7 bc"
  - HOST=x86_64-unknown-linux-gnu PACKAGES=""
  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
    libz-dev libbz2-dev libtiff-tools python python-dev python-setuptools" OSX_SDK=10.9
before_install:
- git clone https://github.com/dashpay/dash_hash
- travis_retry sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- sudo add-apt-repository -y ppa:bitcoin/bitcoin
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
install:
- if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
- sudo apt-get update
- travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
- cd dash_hash && python setup.py install --user && cd ..
before_script:
- unset CC; unset CXX
- cd $TRAVIS_BUILD_DIR
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
script:
- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
- "./autogen.sh"
- cd depends && make $MAKEJOBS $OPT
- cd $TRAVIS_BUILD_DIR && ./configure --prefix=$TRAVIS_BUILD_DIR/depends/$HOST $CONF
- make $MAKEJOBS
before_deploy:
- "chmod +x pre-deploy.sh"    
- "./pre-deploy.sh"
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET
  bucket: $S3_BUCKET
  local_dir: $OUTDIR/zip
  skip_cleanup: true

